// Regenerates sw-files.js: the list of files the installed app keeps offline, plus a
// version hash. Run after changing any file:  node rosenberg-world/tools/build-sw.js
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const root = path.resolve(__dirname, "..");
const skip = new Set(["sw.js", "sw-files.js", "README.md"]);
const files = [];
(function walk(dir) {
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name), rel = path.relative(root, full).split(path.sep).join("/");
    if (name.startsWith(".") || rel.startsWith("tools") || rel.startsWith("games/_template")) continue;
    if (fs.statSync(full).isDirectory()) walk(full);
    else if (!skip.has(rel) && !/\.(md|txt)$/i.test(name)) files.push(rel);
  }
})(root);
const hash = crypto.createHash("sha256");
for (const f of files) hash.update(f).update(fs.readFileSync(path.join(root, f)));
const version = hash.digest("hex").slice(0, 12);
fs.writeFileSync(path.join(root, "sw-files.js"),
  "// Generated by tools/build-sw.js. Do not edit by hand.\n" +
  `self.RW_VERSION = "${version}";\n` +
  `self.RW_FILES = ${JSON.stringify(["./", ...files], null, 0).replace(/","/g, '",\n  "')};\n`);
// stamp sw.js too, so every browser sees a changed service worker and updates
const swPath = path.join(root, "sw.js");
fs.writeFileSync(swPath, fs.readFileSync(swPath, "utf8").replace(/^\/\/ build: .*\n/m, "").replace(/^/, `// build: ${version}\n`));
console.log(`sw-files.js: ${files.length} files, version ${version}`);
