// build: fdfb2ef7f582
// Rosenberg World service worker: keeps every file on the iPad so the world and all
// its games work offline once installed. sw-files.js is generated by tools/build-sw.js
// (it lists every file and a version that changes whenever any file changes).
importScripts("sw-files.js");
const CACHE = "rw-" + self.RW_VERSION;
const FONTS = "rw-fonts";

self.addEventListener("install", (ev) => {
  ev.waitUntil(caches.open(CACHE).then((c) => c.addAll(self.RW_FILES)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (ev) => {
  ev.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONTS).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("fetch", (ev) => {
  const req = ev.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  // Google Fonts: keep a copy the first time they load
  if (/fonts\.(googleapis|gstatic)\.com$/.test(url.hostname)) {
    ev.respondWith(caches.open(FONTS).then(async (c) => {
      const hit = await c.match(req);
      if (hit) return hit;
      try { const res = await fetch(req); if (res.ok || res.type === "opaque") c.put(req, res.clone()); return res; } catch (e) { return hit || Response.error(); }
    }));
    return;
  }
  if (url.origin !== location.origin) return;
  // our own files: straight from the iPad (ignoring ?player=... on game pages), the network as a backup
  ev.respondWith(caches.open(CACHE).then(async (c) => {
    const hit = await c.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try { return await fetch(req); } catch (e) { return (await c.match("./index.html")) || Response.error(); }
  }));
});
